#pragma once
#define  RPL_WELCOME(username) ("001 :"+username)
#define  ERR_PASSWMISMATCH ":server 464* : Incorrect Password"
#define  ERR_UNKNOWNCOMMAND ":server 421 * : Please enter the PASS command"
#define RPL_YOURHOST "002 : <client> :Your host is <servername>, running version <version>"
#define RPL_CREATED "003 : <client> :This server was created <datetime>"
#define RPL_MYINFO "004 : <client> <servername> <version> <available user modes> <available channel modes> [<channel modes with a parameter>]"
#define RPL_ISUPPORT "005 : <client> <1-13 tokens> :are supported by this server"
#define RPL_BOUNCE "010 : <client> <hostname> <port> :<info>"
#define RPL_STATSCOMMANDS "212 : <client> <command> <count> [<byte count> <remote count>]"
#define RPL_ENDOFSTATS "219 : <client> <stats letter> :End of /STATS report"
#define RPL_UMODEIS "221 : <client> <user modes>"
#define RPL_STATSUPTIME "242 : <client> :Server Up <days> days <hours>:<minutes>:<seconds>"
#define RPL_LUSERCLIENT "251 : <client> :There are <u> users and <i> invisible on <s> servers"
#define RPL_LUSEROP "252 : <client> <ops> :operator(s) online"
#define RPL_LUSERUNKNOWN "253 : <client> <connections> :unknown connection(s)"
#define RPL_LUSERCHANNELS "254 : <client> <channels> :channels formed"
#define RPL_LUSERME "255 : <client> :I have <c> clients and <s> servers"
#define RPL_ADMINME "256 : <client> [<server>] :Administrative info"
#define RPL_ADMINLOC1 "257 : <client> :<info>"
#define RPL_ADMINLOC2 "258 : <client> :<info>"
#define RPL_ADMINEMAIL "259 : <client> :<info>"
#define RPL_TRYAGAIN "263 : <client> <command> :Please wait a while and try again."
#define RPL_LOCALUSERS "265 : <client> [<u> <m>] :Current local users <u>, max <m>"
#define RPL_GLOBALUSERS "266 : <client> [<u> <m>] :Current global users <u>, max <m>"
#define RPL_WHOISCERTFP "276 : <client> <nick> :has client certificate fingerprint <fingerprint>"
#define RPL_NONE "300 : Undefined format"
#define RPL_AWAY "301 : <client> <nick> :<message>"
#define RPL_USERHOST "302 : <client> :[<reply>{ <reply>}]"
#define RPL_UNAWAY "305 : <client> :You are no longer marked as being away"
#define RPL_NOWAWAY "306 : <client> :You have been marked as being away"
#define RPL_WHOISREGNICK "307 : <client> <nick> :has identified for this nick"
#define RPL_WHOISUSER "311 : <client> <nick> <username> <host> * :<realname>"
#define RPL_WHOISSERVER "312 : <client> <nick> <server> :<server info>"
#define RPL_WHOISOPERATOR "313 : <client> <nick> :is an IRC operator"
#define RPL_WHOWASUSER "314 : <client> <nick> <username> <host> * :<realname>"
#define RPL_ENDOFWHO "315 : <client> <mask> :End of WHO list"
#define RPL_WHOISIDLE "317 : <client> <nick> <secs> <signon> :seconds idle, signon time"
#define RPL_ENDOFWHOIS "318 : <client> <nick> :End of /WHOIS list"
#define RPL_WHOISCHANNELS "319 : <client> <nick> :[prefix]<channel>{ [prefix]<channel>}"
#define RPL_WHOISSPECIAL "320 : <client> <nick> :blah blah blah"
#define RPL_LISTSTART "321 : <client> Channel :Users  Name"
#define RPL_LIST "322 : <client> <channel> <client count> :<topic>"
#define RPL_LISTEND "323 : <client> :End of /LIST"
#define RPL_CHANNELMODEIS "324 : <client> <channel> <modestring> <mode arguments>..."
#define RPL_CREATIONTIME "329 : <client> <channel> <creationtime>"
#define RPL_WHOISACCOUNT "330 : <client> <nick> <account> :is logged in as"
#define RPL_NOTOPIC "331 : <client> <channel> :No topic is set"
#define RPL_TOPIC "332 : <client> <channel> :<topic>"
#define RPL_TOPICWHOTIME "333 : <client> <channel> <nick> <setat>"
#define RPL_INVITELIST "336 : <client> <...>"
#define RPL_ENDOFINVITELIST   "337 : <client> :End of /INVITE list"
#define RPL_WHOISACTUALLY   "338 : <client> <nick> :is actually ..."
#define RPL_INVITING    "341 : <client> <nick> <channel>"
#define RPL_INVEXLIST  "346 : <client> <channel> <mask>"
#define RPL_ENDOFINVEXLIST    "347 : <client> <channel> :End of Channel Invite Exception List"
#define RPL_EXCEPTLIST    "348 : <client> <channel> <mask>"
#define RPL_ENDOFEXCEPTLIST    "349 : <client> <channel> :End of channel exception list"
#define RPL_VERSION   "351 : <client> <version> <server> :<comments>"
#define RPL_WHOREPLY    "352 : <client> <channel> <username> <host> <server> <nick> <flags> :<hopcount> <realname>"
#define RPL_NAMREPLY   "353 : <client> <symbol> <channel> :[prefix]<nick>{ [prefix]<nick>}"
#define RPL_LINKS     "364 : <client> * <server> :<hopcount> <server info>"

#define RPL_ENDOFLINKS "<client> * :End of /LINKS list"
#define RPL_ENDOFNAMES "<client> <channel> :End of /NAMES list"
#define RPL_BANLIST "<client> <channel> <mask> [<who> <set-ts>]"
#define RPL_ENDOFBANLIST "<client> <channel> :End of channel ban list"
#define RPL_ENDOFWHOWAS "<client> <nick> :End of WHOWAS"
#define RPL_INFO "<client> :<string>"
#define RPL_MOTD "<client> :<line of the motd>"
#define RPL_ENDOFINFO "<client> :End of INFO list"
#define RPL_MOTDSTART "<client> :- <server> Message of the day - "
#define RPL_ENDOFMOTD "<client> :End of /MOTD command."
#define RPL_WHOISHOST "<client> <nick> :is connecting from *@localhost 127.0.0.1"
#define RPL_WHOISMODES "<client> <nick> :is using modes +ailosw"
#define RPL_YOUREOPER "<client> :You are now an IRC operator"
#define RPL_REHASHING "<client> <config file> :Rehashing"
#define RPL_TIME "<client> <server> [<timestamp> [<TS offset>]] :<human-readable time>"
#define ERR_UNKNOWNERROR "<client> <command>{ <subcommand>} :<info>"
#define ERR_NOSUCHNICK "<client> <nickname> :No such nick/channel"
#define ERR_NOSUCHSERVER "<client> <server name> :No such server"
#define ERR_NOSUCHCHANNEL "<client> <channel> :No such channel"
#define ERR_CANNOTSENDTOCHAN "<client> <channel> :Cannot send to channel"
#define ERR_TOOMANYCHANNELS "<client> <channel> :You have joined too many channels"
#define ERR_WASNOSUCHNICK "<client> :There was no such nickname"
#define ERR_NOORIGIN "<client> :No origin specified"
#define ERR_NORECIPIENT "<client> :No recipient given (<command>)"
#define ERR_NOTEXTTOSEND "<client> :No text to send"
#define ERR_INPUTTOOLONG "<client> :Input line was too long"
#define ERR_NOMOTD "<client> :MOTD File is missing"
#define ERR_NONICKNAMEGIVEN "<client> :No nickname given"
#define ERR_ERRONEUSNICKNAME "<client> <nick> :Erroneus nickname"
#define ERR_NICKNAMEINUSE "<client> <nick> :Nickname is already in use"
#define ERR_NICKCOLLISION "<client> <nick> :Nickname collision KILL from <user>@<host>"
#define ERR_USERNOTINCHANNEL "<client> <nick> <channel> :They aren't on that channel"
#define ERR_NOTONCHANNEL "<client> <channel> :You're not on that channel"
#define ERR_USERONCHANNEL "<client> <nick> <channel> :is already on channel"
#define ERR_NOTREGISTERED "<client> :You have not registered"
#define ERR_NEEDMOREPARAMS "<client> <command> :Not enough parameters"
#define ERR_ALREADYREGISTERED "<client> :You may not reregister"
#define ERR_PASSWDMISMATCH "<client> :Password incorrect"
#define ERR_YOUREBANNEDCREEP "<client> :You are banned from this server."
#define ERR_CHANNELISFULL "<client> <channel> :Cannot join channel (+l)"
#define ERR_UNKNOWNMODE "<client> <modechar> :is unknown mode char to me"
#define ERR_INVITEONLYCHAN "<client> <channel> :Cannot join channel (+i)"
#define ERR_BANNEDFROMCHAN "<client> <channel> :Cannot join channel (+b)"
#define ERR_BADCHANNELKEY "<client> <channel> :Cannot join channel (+k)"
#define ERR_BADCHANMASK "<channel> :Bad Channel Mask"
#define ERR_NOPRIVILEGES "<client> :Permission Denied- You're not an IRC operator"
#define ERR_CHANOPRIVSNEEDED "<client> <channel> :You're not channel operator"
#define ERR_CANTKILLSERVER "<client> :You cant kill a server!"
#define ERR_NOOPERHOST "<client> :No O-lines for your host"
#define ERR_UMODEUNKNOWNFLAG "<client> :Unknown MODE flag"
#define ERR_USERSDONTMATCH "<client> :Cant change mode for other users"
#define ERR_HELPNOTFOUND "<client> <subject> :No help available on this topic"
#define ERR_INVALIDKEY "<client> <target chan> :Key is not well-formed"
#define RPL_STARTTLS "<client> :STARTTLS successful, proceed with TLS handshake"
#define RPL_WHOISSECURE "<client> <nick> :is using a secure connection"
#define ERR_STARTTLS "<client> :STARTTLS failed (Wrong moon phase)"
#define ERR_INVALIDMODEPARAM "<client> <target chan/user> <mode char> <parameter> :<description>"
#define RPL_HELPSTART "<client> <subject> :<first line of help section>"
#define RPL_HELPTXT "<client> <subject> :<line of help text>"
#define RPL_ENDOFHELP "<client> <subject> :<last line of help text>"
#define ERR_NOPRIVS "<client> <priv> :Insufficient oper privileges."
#define RPL_LOGGEDIN "<client> <nick>!<user>@<host> <account> :You are now logged in as <username>"
#define RPL_LOGGEDOUT "<client> <nick>!<user>@<host> :You are now logged out"
#define ERR_NICKLOCKED "<client> :You must use a nick assigned to you"
